apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: udcl0oz82-go
  janus-idp.io/tekton: udcl0oz82-go
  backstage.io/kubernetes-id: udcl0oz82-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: udcl0oz82-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
